name: Build Nextcloud Image

on:
  push:
    branches: [main, dev]
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    permissions:
      contents: read
      actions: read
      packages: write
      id-token: write
    uses: MArpogaus/image-builder-action/.github/workflows/build-and-publish.yml@main
    with:
      image-name: my-nextcloud
      containerfile: ./Containerfile
      context: .
      platform: linux/amd64
      build-args: |
        NEXTCLOUD_TAG=31
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
